CREATE TABLE [dbo].[Cart] (
    [Id]     INT NOT NULL IDENTITY,
    [UserId] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Cart_User] FOREIGN KEY ([UserId]) REFERENCES [User](Id)
);